name: CI 2° Step - Docker Job

on:
  workflow_call:

jobs:
  DockerPush:
    name: Docker job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Log into registry
        run: echo "${{ secrets.GH_ACCESS_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GH_USERNAME }}" --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}
          docker tag my-app:latest $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
